### PR TITLE
2115: Updated TE filters (Drawer)

### PR DESCRIPTION
**Pull request by Sun-Mountain**
Applying new design for the search results page, where the filters are in a drawer.

The filters are currently broken as this layout is better suited for the filtering to happen in the backend which ill be applied in [1680](https://fearless.jira.com/browse/NJWE-1680).

Expected filter behavior is changing the search query changes the search. Changing anything else will result in a different URL.

### CODE REVIEW

**Review by ChelseaKR — CHANGES_REQUESTED** [review]
Looks really good! A few things I noticed we gotta fix before it's approved:

- Time to complete filter isn't manipulating the URL properly, giving me parameters like `training/search?q=cdl&miles=10&zipcode=07030&completeIn=%5Bobject+Object%5D` - in production it's set up as boolean flags for each time length
- Same behavior happening for languages, provider services
- Please use i18n resource strings wherever possible - I did a few of these for you

Otherwise, looks good to me. Thank you so much @Sun-Mountain !!

**Comment by Sun-Mountain** [comment]
> Looks really good! A few things I noticed we gotta fix before it's approved:
> 
>     * Time to complete filter isn't manipulating the URL properly, giving me parameters like `training/search?q=cdl&miles=10&zipcode=07030&completeIn=%5Bobject+Object%5D` - in production it's set up as boolean flags for each time length
> 
>     * Same behavior happening for languages, provider services
> 
>     * Please use i18n resource strings wherever possible - I did a few of these for you
> 
> 
> Otherwise, looks good to me. Thank you so much @Sun-Mountain !!

Fixed all of the above!

**Comment by mflymfly** [comment]
1:03 load time when searching for Nurse. Can this be improved?

All
* Change “Search by training, provider, certification, SOC code, or keyword” > “Search by training, provider, certification, SOC code, CIP code, or keyword”
* Make filter labels sentence case
* Need to include filter chips so users know what filters are applied
    * May require a separate / follow up ticket but should not launch without it 
image (4)

Desktop
* Sticky header and footer of drawer full width 

Mobile
* Filter drawer 95vh max heights
* Sticky header of drawer full width

**Review by ChelseaKR — APPROVED** [review]

**Comment by ChelseaKR** [comment]
Reassigning followup to @scwambach

**Pull request merged**
