### PR TITLE
Career Pathways Update

### PR DESCRIPTION
**Pull request by scwambach**
Resolves - [NJWE-2348](https://fearless.jira.com/browse/NJWE-2348) & [NJWE-2349](https://fearless.jira.com/browse/NJWE-2349)

# What I did:
- Updated the look of career pathways as per the [Figma design file](https://www.figma.com/design/OpDXhA1U39JMQowgtLy0hF/4---MCNJ---Dev-File?node-id=20505-23348&t=2l9ijNsjz4LpRwQC-1)
- [ ] Dev Review
- [x] Design Review

### CODE REVIEW

**Review by mflymfly — CHANGES_REQUESTED** [review]
Looking great so far. Added my notes in a previous comment.

**Review by mflymfly — CHANGES_REQUESTED** [review]
_Looking superb. Just a couple small fixes:_

**Tooltip**

- [x] Tooltip text is on one line and should wrap. I don't see any USDWS tooltip size guidelines so we can use maximum width of a tooltip 160 px on desktop, 200 px on mobile.
Screenshot 2024-10-01 at 8 02 47 AM

**Expand map button** 

- [x] map is repeated twice (remove the bold "map")
- [x] make font 14px
- [x] mobile: remove pathways name (see screenshot)

Screenshot 2024-10-01 at 8 34 47 AM



**Map scroll behavior**

- [x] Since the user is technically interacting with the items on the map once they use the dropdown lets have the map scrolled to once a user selects a dropdown item. Let me know if you want to chat through this behavior a little more. Might be easier to just talk it through.
First: 
image
After: 
image


**Tab Focus**

- [x] Field check boxes not focused on tab

image

- [x] Rogue X showing up when an occupation is selected

image

- [x] Arrows not faded out when tray opens
image

**Related Training Opportunities Box**

- [x] Remove up out arrow but make sure each of these opens a new tab

image

**Salary Range**

- [x] Not showing for most occupations

image

**Bottom Margin for Map Details**

- [x] Add 48px margin (spacing between bottom of map details and top of footer

**Spacing between dropdown and map**

- [x] 48px spacing (see screenshot)

image

**Comment by mflymfly** [comment]
@scwambach - sorry but one more small update for the Healthcare and TDL pages.

image

- [ ] Remove subtext
- [ ] Remove divider
- [ ] Change TDL in h2 to full name of industry for that page
- [ ] Remove help text over dropdown since it matches the h2 text

**Review by mflymfly — APPROVED** [review]
LGTM! < Ignore, I found just a couple more items and then we should be good

**Review by mflymfly — CHANGES_REQUESTED** [review]
- [ ] Placeholder text on dropdown should be grey until a user selects an occupation `#757575` (may already be a system grey, maybe labeled base)

image

- [ ] Industry drawer looks like it is greyed out and non scrollable when open

image

- [ ] Focus state color of radio box does not match the other buttons

Screenshot 2024-10-02 at 7 51 22 AM

### **Details buttons**

image

- [ ] Training button link is missing query parameter in url so opens as an error
- [ ] Assistance button should go to `/support-resources/tuition-assistance`. currently it goes to `/tuition-assistance`

**Review by mflymfly — CHANGES_REQUESTED** [review]
Last three things:

- [x] When a user tabs to focus on the a radiobox, pressing enter does not select it

- [x] Healtcare and TDL dropdown also should have grey text when nothing sleected
image

- [x] The industry drawer content is not syncing with Contentful. 
image

### If light lift can we do the following?

- [x] A: if no salary range data then hide the zero
- [x] B: if no salary data then change --- to "Salary data not available"
- [ ] C: If cost = $0 then remove the zero and gray box


image

**Review by mflymfly — APPROVED** [review]
LGTM!

**Review by ChelseaKR — APPROVED** [review]
LGTM

**Pull request merged**
