### PR TITLE
NJWE 2452 training page design update

### PR DESCRIPTION
**Pull request by scwambach**
resolves [NJWE-2452](https://fearless.jira.com/browse/NJWE-2452)
# What I did:
- updated the design of the training pages
- added search function the heading area
- [x] Design review
- [ ] Dev review

### CODE REVIEW

**Review by ChelseaKR — APPROVED** [review]
Looks amazing to me. Thank you so much!!

**Review by mflymfly — CHANGES_REQUESTED** [review]
### Global

- [ ] Please refer to section subheadings at this [link](https://www.figma.com/design/OpDXhA1U39JMQowgtLy0hF/4---Dev-File?node-id=21964-12195&node-type=frame&t=AkqHYrwtVYTkKGHK-11) to fix punctuation and capitalization

Cost (see [mockup](https://www.figma.com/design/OpDXhA1U39JMQowgtLy0hF/4---Dev-File?node-id=21964-12195&node-type=frame&t=AkqHYrwtVYTkKGHK-11))

- [x] Add divider between total and itemized list
- [x] Add light dash line to listed items(spans label and cost)

Instructional Programs section: 

- [ ] Make 'Classification of Instructional Programs' text the CIP code drawer

Associated Occupations and Industries section: 
- [ ] Make `Standard Occupational Classification` text a drawer ([Link to Drawer copy and design](https://www.figma.com/design/OpDXhA1U39JMQowgtLy0hF/4---Dev-File?node-id=21988-9324&node-type=section&t=AkqHYrwtVYTkKGHK-11))
- [ ] Links should open in new tab

How to Get Funding section: 
- [x] update spacing per notation on section
- [x] Make `View tuition resource page` open in new tab
- [ ] Change `New Jersey's One-Stop Career Centers` to `Contact One-Stop Career Centers`
- [ ] Make both buttons Unstyled (underlined)

Support Services:

- [ ] Change description to `Support services provided for the learning opportunity`

### Mobile
Search Button and Breadcrumbs:

- [ ] Make Search Icon 32px x 32px
- [ ] Tray should slide in
- [ ] Not sure exactly where the extra padding is coming from but the height of this section is pretty large. I think we can lower the padding to .5rem or just make the max height something closer to what we want (48px?)

Cost:

- [ ] Move to under Quick Facts on Mobile

General on Mobile

- [ ] This may just be my device or browser but it looks like the width is a little odd. I can a scroll a bit horizontally but not sure what is causing that.

**Review by mflymfly — CHANGES_REQUESTED** [review]
Looking great. Just a few things popped up while testing:

Support services

- [x] Add a period to "Services are subject to provider details..." sentence in this box

SOC and CIP

- [x] Please style the underlined drawer like the Employment and Salary boxes (Dotted line, see below)
- [x] I think the drawer is also a different style. The Employment drawer is 50vw but the SOC and CIP drawers are 100vw. 
- [x] Please deactivate scrolling of page while drawer is open

Stat Block

- [x] Make all text 1rem
image


Title Box

- [x] Mobile: Because of the lengths of some of the `titles` and `locations`, I am worried the title box will take up more real estate on the page than we want (especially on smaller devices). Lets **remove the sticky property when on mobile devices**. I will create a follow up ticket to solve this but for now lets just deactivate that.
- [x] Mobile: stack copy and print buttons vertically

Search Bar

- [ ] Desktop: pressing enter while focused on input does not submit results
- [ ] Mobile: Drawer should animate in when search pressed
- [ ] Mobile: It looks like the search button shifts after clicking it. Not really sure why though.

Search Result Behavior Oddities. These may just be test environment / sandbox issues

- [ ] When a filter is selected the amount old pages doesn't reduce. It looks like each training remains on its original page #
- [ ] Training pages for trainings not marked in-demand are not loading content

Additional differences between desktop and mobile (may just be my device)

- [x] On safari for iOS, my CIP, SOC, andSearch button are 
all blue. That may just be a specific thing for my device but just wanted to call that out. undefined  Training  My Career NJ

**Comment by ChelseaKR** [comment]
@mflymfly 

>  Training pages for trainings not marked in-demand are not loading content

I'm unable to reproduce this - can you provide an example?

**Review by mflymfly — CHANGES_REQUESTED** [review]
Found two more things on mobile:

- [x] Some icons on mobile are tiny in the quick facts section
Screenshot 2024-12-04 at 7 49 43 AM

- [x] Clicking the close button on the search drawer does not close the drawer, it instead sends the user back to the search page

Previous note: SOC and CIP

- [x] Please style the underlined drawer like the Employment and Salary boxes (Dotted line, see below)

**Review by mflymfly — APPROVED** [review]

**Pull request merged**
