### PR TITLE
NJWE-2324 - redesign TE page

### PR DESCRIPTION
**Pull request by scwambach**
Resolves [NJWE-2324](https://fearless.jira.com/browse/NJWE-2324)
# What I did:
- gave TE page a new design to top section of the page
- [x] Design Review
- [ ] Dev Review

### CODE REVIEW

**Review by mflymfly — CHANGES_REQUESTED** [review]
This is looking really good. Just a few small changes.

- [x] - Sentence case for step 2: `
Filter and compare results`
- [x] - Sentence case for step 3: `
Visit training provider’s website to enroll`
- [x] Learn more link goes to > `/faq#etpl-program-general-information`
- [x] Search for jobs button > `https://www.careeronestop.org/Toolkit/Jobs/find-jobs-results.aspx?keyword=&location=New%20Jersey&radius=25&source=NLX&curPage=1&referer=%2FToolkit%2FJobs%2Ffind-jobs.aspx`
- [x] Tuition button `/support-resources/tuition-assistance`
- [x] Info icon next to Search for Training > Use USWDS style tooltip
- [x] Make info icon focusable on tab

One note: we will need to add in spanish translations. I will work with Jewel on how to get those.

**Review by mflymfly — CHANGES_REQUESTED** [review]
- [ ] It looks like the tooltip got removed from the mobile view
- [x] sentence case `Search for training`
- [ ] Sentence case `Clear all`
- [ ] Sentence case `Miles from ZIP code`
- [ ] Sentence case `Max cost`
- [ ] Sentence case `Class format`
- [ ] Sentence case `In-person`

**Review by mflymfly — APPROVED** [review]
LGTM!

**Comment by ChelseaKR** [comment]
@scwambach can you plz clean up the failing Cypress tests before I review? tysm

**Review by ChelseaKR — APPROVED** [review]

**Pull request merged**
