### PR TITLE
NJWE-1807 - default og tags

### PR DESCRIPTION
**Pull request by scwambach**
related to [NJWE-1807](https://fearless.jira.com/browse/NJWE-1807)

## What I did:
- created default hard coded seo data as a stop-gap to ensure better shareability
- The hardcoded data is overwritten once the page loads, but the page data needs to be "Hydrated" in order to see it. That's why nothing/wrong info shows up
- this will ensure that something relavant will appear
- the images that I chose to use are just screen grabs of the page, we can replace those as soon as something is ready
- [ ] Dev review 
- [ ] Design review

### CODE REVIEW

**Review by mflymfly — COMMENTED** [review]
Is there a way I can test this locally?

**Review by ChelseaKR — APPROVED** [review]
LGTM

**Comment by ChelseaKR** [comment]
@mflymfly I can put this in the user research branch if you'd like? or we can schedule some Zoom time to go over together

**Comment by mflymfly** [comment]
@ChelseaKR just not sure how to go about testing so whatever works

**Pull request merged**
