### PR TITLE
NJWE 2334 - loading screen

### PR DESCRIPTION
**Pull request by scwambach**
Resolves [NJWE-2334](https://fearless.jira.com/browse/NJWE-2334)

# What I did:
- Replaced the spinning loading circle icon with a "skeleton" of the result card for better user feed back
- [ ] Design Review
- [ ] Dev Review

### CODE REVIEW

**Comment by ChelseaKR** [comment]
@mflymfly do you think the skeleton should appear for every page load (even when cached)? When pages are loaded with cached results it shows the skeleton for a flash and then the real results, causing unnecessary content draw and possibly disorienting to the user (instead of the previous behavior)

**Review by ChelseaKR — CHANGES_REQUESTED** [review]
Looks excellent! Only change request I have- could you please change the "Searching training data for your results..." and "This may take a few seconds" static text into i18next resources w/ translations? Feel free to use Google Translate b/c we're in difficult times

**Comment by mflymfly** [comment]
> @mflymfly do you think the skeleton should appear for every page load (even when cached)? When pages are loaded with cached results it shows the skeleton for a flash and then the real results, causing unnecessary content draw and possibly disorienting to the user (instead of the previous behavior)

That's a good point. Yeah let's make it not show in those instances.

**Review by mflymfly — CHANGES_REQUESTED** [review]
This is looking really great. 

Only change I have is the note that Chelsea left above regarding not showing the loader for cached results.

I also noticed something odd when testing mobile (and also happened on desktop). The page says there are `142 results` but they end on page 3 and there are none on page 4
image

The url for the issue was: http://localhost:3000/training/search?q=cdl&inDemand=true&p=3&format=online

**Comment by scwambach** [comment]
> I also noticed something odd when testing mobile (and also happened on desktop). The page says there are `142 results` but they end on page 3 and there are none on page 4

@mflymfly This looks like it's due to the pagination and page count not being setup properly. It's getting the result count from `cdl` and not the count of `cdl` + all the filters. Should I go ahead tackle that within in this ticket?

> do you think the skeleton should appear for every page load (even when cached)?

@ChelseaKR how would I go about targeting that?

**Comment by mflymfly** [comment]
Sorry @scwambach - I didn't see the pagination question in your comment. I don't think it needs to happen in this ticket but we should do a follow up for it for sure since it is a bug.

**Review by mflymfly — COMMENTED** [review]
My eyes may be deceiving me but I think I am still seeing the skeleton loader flash for a milisecond when changing to a cached page.

**Comment by scwambach** [comment]
> My eyes may be deceiving me but I think I am still seeing the skeleton loader flash for a milisecond when changing to a cached page.


https://github.com/user-attachments/assets/cc5ee953-e230-4e50-b6bc-c3f79da49b4e

Here's a screen recording I made of me refreshing the page with and then without the check for cached data. You can see the loading screen come back in only when it's disabled. Is that now what you were seeing?

**Review by mflymfly — APPROVED** [review]
LGTM

**Review by ChelseaKR — APPROVED** [review]

**Pull request merged**
