### PR TITLE
NJWE-1879 How to get funding

### PR DESCRIPTION
**Pull request by scwambach**
Resolves [NJWE-1879](https://fearless.jira.com/browse/NJWE-1879)
## What I did:
- On the Training Explorer (TE) page, the section currently called “sign up for this training' in the live site will have different verbiage, and two buttons to access tuition assistance info will be introduced (See [Figma file](https://www.figma.com/file/OpDXhA1U39JMQowgtLy0hF/4---MCNJ---Dev-File?type=design&node-id=17970-9104&mode=design))
- Frist button (Contact Career One Stop) will link to [Career One Stop Contact Form](https://forms.office.com/Pages/ResponsePage.aspx?id=0cN2UAI4n0uzauCkG9ZCp9aufXmVjuxHue2STv_YxBxUNDM2V1UwWkQ1QjVES0g2S01FNk03TEVERy4u)
- Second button (View Tuition Assistance Resources) till take users to [MCNJ TA page](https://mycareer.nj.gov/support-resources/tuition-assistance).
- On the TA page, there will be green “Funding for In-Demand Occupations' box that displays ‘only’ when:
  1. User presses the 'View Tuition Assistance Resources' button from TE while browsing an in-demand occupation.
  2. If the user opens TA from another place other than the one mentioned above (1.) and selects 'Job Training' AND/OR 'Grant' (if the user does not select one or both of those options in the filter, the box should not show.)
- [ ] Dev Review
- [ ] Design Review

### CODE REVIEW

**Review by mflymfly — CHANGES_REQUESTED** [review]
**Training Details pages**
[Prototype](https://www.figma.com/proto/OpDXhA1U39JMQowgtLy0hF/4---MCNJ---Dev-File?page-id=17970%3A9104&type=design&node-id=18062-179744&viewport=468%2C1861%2C0.28&t=fDb9xDwpW000oHAN-1&scaling=min-zoom&mode=design)

- [ ] Add copy, print, and save links to header sections

(See this [loom](https://www.loom.com/share/0c8fa6d335894673ad039866124a0e5e?sid=93b45a86-b05c-4005-a4f2-aeaca03e5e1b) link for behavior)

- [ ] Fix hover states of Funding buttons, they should not fill in
- [ ] Change icon to be up external link arrow (see [designs](https://www.figma.com/file/OpDXhA1U39JMQowgtLy0hF/4---MCNJ---Dev-File?type=design&node-id=17970-9107&mode=design&t=SAhYl7dT3XEzzv1C-4))

**Tuition Assistance Page (green Funding card)**
- [x] Green card should show at all times, no matter how you get to the Tuition Assistance page
- [x] Button should open in new tab
- [x] Button should link to [https://forms.office.com/Pages/ResponsePage.aspx?id=0cN2UAI4n0uzauCkG9ZCp9aufXmVjuxHue2STv_YxBxUNDM2V1UwWkQ1QjVES0g2S01FNk03TEVERy4u](url)
- [x] Change icon to be up external link arrow (see designs)

**Comment by ChelseaKR** [comment]
@scwambach is this ready for @mflymfly's re-review? would actually like to get his approval before doing dev review

**Review by mflymfly — CHANGES_REQUESTED** [review]
- [x] [Just some small spacing / padding updates for the section](https://www.figma.com/file/OpDXhA1U39JMQowgtLy0hF/4---MCNJ---Dev-File?type=design&node-id=18281-34023&mode=design&t=tbtubXpn5VlBVHoM-4)

Mobile Only
- [x] Make How to Get Funding section the last section of the list
- [x] Looks like the headers are no longer sticking to top on scroll
- [x] How to Get Funding section - Buttons can hug text, does not need to be full width of container

**Review by mflymfly — CHANGES_REQUESTED** [review]
- [ ] Just remove the green funding box and we will be G2G

**Review by mflymfly — APPROVED** [review]
LGTM!

**Review by Sun-Mountain — APPROVED** [review]
⭐

**Pull request merged**
