### PR TITLE
NJWE-1833 & NJWE-1823 CIP Code info drawer

### PR DESCRIPTION
**Pull request by scwambach**
resolves [NJWE-1833](https://fearless.jira.com/browse/NJWE-1833) & [NJWE-1823](https://fearless.jira.com/browse/NJWE-1823)
# What I did:
- altered the CIP code information in the training detail page
- added an info drawer
- linked the CIP code to the CIP code website page
- added the decimal point into the code
- updated the Search results with new CIP code design
- [x] Dev Review
- [ ] Design Review

### CODE REVIEW

**Comment by mflymfly** [comment]
I am not getting any results when making a search

**Comment by ChelseaKR** [comment]
@mflymfly you've been able to run searches on our Credential Engine branch before, right? I'm not able to reproduce that here

**Comment by mflymfly** [comment]
I am not sure if I have or not. I am also now getting this error:you need to resolve your current index first
frontend/package-lock.json: needs merge

**Comment by ChelseaKR** [comment]
@mflymfly try running this command in a terminal:

` rm -rf backend/node_modules backend/package-lock.json frontend/node_modules frontend/package-lock.json && ./scripts/install-all.sh 
`

and then relaunch the app

**Review by mflymfly — CHANGES_REQUESTED** [review]
Looks really good. Only issue I see is that the popover text needs to be updated to this:
image

[Link to FIGMA](https://www.figma.com/file/OpDXhA1U39JMQowgtLy0hF/4---MCNJ---Dev-File?type=design&node-id=17769-1352&mode=design&t=yHJ66ZXym2chCgrc-4)

For the detail section, can we move the code next to the CIP code label so it matches the layout of the parts above.

image


[FIGMA DESIGN](https://www.figma.com/file/OpDXhA1U39JMQowgtLy0hF/4---MCNJ---Dev-File?type=design&node-id=17912-6382&mode=design&t=yHJ66ZXym2chCgrc-4)

**Review by ChelseaKR — APPROVED** [review]

**Pull request merged**
